# Generated by Django 6.0.6 on 2026-06-16 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_approved', 'Request Approved'), ('approval_rejected', 'Request Rejected'), ('approval_pending', 'Approval Pending'), ('low_stock', 'Low Stock Alert'), ('bin_full', 'Bin Full Alert'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('purchase_order_approved', 'Purchase Order Approved'), ('inventory_mismatch', 'Inventory Mismatch'), ('general', 'General')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
