# Generated by Django 6.0.6 on 2026-06-16 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('commented', 'Commented')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='note',
            new_name='reviewer_note',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='purchase_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='reference_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='stock_movement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('inventory_adjustment', 'Inventory Adjustment'), ('stock_transfer', 'Stock Transfer'), ('bin_capacity_change', 'Bin Capacity Change'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='approvals_a_status_06b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['request_type'], name='approvals_a_request_c0c59b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by'], name='approvals_a_request_da05c5_idx'),
        ),
        migrations.AddField(
            model_name='approvalaudittrail',
            name='approval_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='approvals.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvalaudittrail',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
