# Generated by Django 6.0.6 on 2026-06-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['rack'], name='warehouses__rack_id_1c4c54_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['code'], name='warehouses__code_fc0067_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['zone'], name='warehouses__zone_id_d20a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouses__code_d781d4_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='warehouses__name_add6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['warehouse'], name='warehouses__warehou_9d89b1_idx'),
        ),
    ]
